using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Flowline.SourceGenerators;

[Generator]
public class CustomApiMappingGenerator : IIncrementalGenerator
{
    private const string RequestParameterAttribute = "RequestParameterAttribute";
    private const string ResponsePropertyAttribute = "ResponsePropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classDeclarations.Collect(), static (spc, source) => Execute(source, spc));
    }

    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;
        var symbol = model.GetDeclaredSymbol(classDeclaration);

        if (symbol is not INamedTypeSymbol classSymbol) return null;

        foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (HasMappingAttribute(member))
            {
                return classSymbol;
            }
        }

        return null;
    }

    private static bool HasMappingAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(a => 
            a.AttributeClass?.Name == RequestParameterAttribute || 
            a.AttributeClass?.Name == ResponsePropertyAttribute);
    }

    private static void Execute(ImmutableArray<INamedTypeSymbol?> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty) return;

        var distinctClasses = classes.Where(c => c is not null).Distinct<INamedTypeSymbol?>(SymbolEqualityComparer.Default);

        foreach (var classSymbol in distinctClasses)
        {
            if (classSymbol is null) continue;

            var code = GenerateCode(classSymbol);
            var fullClassName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "")
                .Replace("<", "_")
                .Replace(">", "_");
            context.AddSource($"{fullClassName}.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }

    private static string GenerateCode(INamedTypeSymbol classSymbol)
    {
        var ns = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;

        var requestParams = new List<IPropertySymbol>();
        var responseProps = new List<IPropertySymbol>();

        foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.GetAttributes().Any(a => a.AttributeClass?.Name == RequestParameterAttribute) && member.SetMethod is not null)
                requestParams.Add(member);
            if (member.GetAttributes().Any(a => a.AttributeClass?.Name == ResponsePropertyAttribute) && member.GetMethod is not null)
                responseProps.Add(member);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Xrm.Sdk;");
        sb.AppendLine("using Flowline.Attributes;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static class {className}GeneratedExtensions");
        sb.AppendLine("    {");

        // LoadRequestParameters
        sb.AppendLine($"        public static void LoadRequestParameters(this IPluginExecutionContext context, {className} target)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (context == null) throw new ArgumentNullException(nameof(context));");
        sb.AppendLine("            if (target == null) throw new ArgumentNullException(nameof(target));");
        sb.AppendLine();

        foreach (var prop in requestParams)
        {
            var key = ToCamelCase(prop.Name);
            sb.AppendLine($"            if (context.InputParameters.Contains(\"{key}\"))");
            sb.AppendLine($"                target.{prop.Name} = ({prop.Type.ToDisplayString()})context.InputParameters[\"{key}\"];");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // StoreResponseProperties
        sb.AppendLine($"        public static void StoreResponseProperties(this IPluginExecutionContext context, {className} target)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (context == null) throw new ArgumentNullException(nameof(context));");
        sb.AppendLine("            if (target == null) throw new ArgumentNullException(nameof(target));");
        sb.AppendLine();

        foreach (var prop in responseProps)
        {
            var key = ToCamelCase(prop.Name);
            sb.AppendLine($"            context.OutputParameters[\"{key}\"] = target.{prop.Name};");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToCamelCase(string name) =>
        string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);
}
