using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;
using Flowline.Core;
using Spectre.Console;

namespace Flowline.Services;

public class DataverseContextGenerator(IAnsiConsole console, FlowlineRuntimeOptions runtimeOptions)
{
    static readonly Regex GuidPattern = new(
        @"\{?[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\}?",
        RegexOptions.Compiled);

    public async Task GenerateAsync(
        string packageSrcPath,
        string solutionName,
        string repoRootPath,
        CancellationToken ct = default)
    {
        var contextFilePath = Path.Combine(repoRootPath, "solutions", solutionName, "DATAVERSE_CONTEXT.md");

        var markdown = AssembleMarkdown(packageSrcPath, solutionName);

        Directory.CreateDirectory(Path.GetDirectoryName(contextFilePath)!);
        await File.WriteAllTextAsync(contextFilePath, markdown, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false), ct);

        if (runtimeOptions.IsVerbose) console.WriteLine();
        console.Verbose($"DATAVERSE_CONTEXT.md written to {Markup.Escape(contextFilePath)}", runtimeOptions);

        await SelfHealAgentsMdAsync(repoRootPath, solutionName, ct);
    }

    // ── AGENTS.md self-heal ──────────────────────────────────────────────────

    internal async Task SelfHealAgentsMdAsync(string repoRootPath, string solutionName, CancellationToken ct)
    {
        var agentsPath = Path.Combine(repoRootPath, "AGENTS.md");
        if (!File.Exists(agentsPath))
        {
            console.Warning($"AGENTS.md not found — run 'flowline clone' to scaffold it.");
            return;
        }

        var content = await File.ReadAllTextAsync(agentsPath, ct);
        var importLine  = $"@solutions/{solutionName}/DATAVERSE_CONTEXT.md";
        var linkLine    = $"- [{solutionName}](solutions/{solutionName}/DATAVERSE_CONTEXT.md)";
        const string SectionHeader = "## Dataverse schema context";

        var changed = false;
        var lines = content.Split('\n').ToList();

        if (!content.Contains(linkLine))
        {
            var sectionIdx = lines.FindIndex(l => l.TrimEnd('\r') == SectionHeader);
            if (sectionIdx < 0)
            {
                // No section yet — append section + link at EOF
                if (lines.Count > 0 && string.IsNullOrWhiteSpace(lines[^1])) { /* already blank */ }
                else lines.Add(string.Empty);
                lines.Add(SectionHeader);
                lines.Add(linkLine);
            }
            else
            {
                // Section exists — insert link after the last existing link in the section
                var insertAt = sectionIdx + 1;
                while (insertAt < lines.Count && lines[insertAt].StartsWith("- "))
                    insertAt++;
                lines.Insert(insertAt, linkLine);
            }
            changed = true;
        }

        if (!content.Contains(importLine))
        {
            if (lines.Count > 0 && !string.IsNullOrWhiteSpace(lines[^1]))
                lines.Add(string.Empty);
            lines.Add(importLine);
            changed = true;
        }

        if (changed)
            await File.WriteAllTextAsync(agentsPath, string.Join('\n', lines), CancellationToken.None);
    }

    // ── Markdown assembly ────────────────────────────────────────────────────

    string AssembleMarkdown(string packageSrcPath, string solutionName)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Dataverse Schema — {solutionName}");
        sb.AppendLine();
        sb.AppendLine($"_Generated by Flowline. Do not hand-edit — regenerated on every `flowline sync`._");
        sb.AppendLine();

        // Solution header
        var solutionXmlPath = Path.Combine(packageSrcPath, "Other", "Solution.xml");
        var solutionXml = TryReadFile(solutionXmlPath);
        var solutionHeader = ReadSolutionHeader(solutionXml);
        if (solutionHeader != null) sb.Append(solutionHeader);
        var publisherPrefix = ReadPublisherPrefix(solutionXml);

        // Entities (attributes, relationships, forms, views)
        var entitiesPath = Path.Combine(packageSrcPath, "Entities");
        if (Directory.Exists(entitiesPath))
        {
            foreach (var entityDir in Directory.EnumerateDirectories(entitiesPath).OrderBy(d => d))
            {
                var entityName = Path.GetFileName(entityDir);
                var entityXmlPath = Path.Combine(entityDir, "Entity.xml");
                var entityXml = TryReadFile(entityXmlPath);
                if (entityXml == null) continue;

                var entitySection = ReadEntity(entityXml, publisherPrefix);
                if (entitySection == null) continue;
                sb.Append(entitySection);

                // Relationships
                var relXmlPath = Path.Combine(packageSrcPath, "Other", "Relationships", $"{entityName}.xml");
                var relXml = TryReadFile(relXmlPath);
                if (relXml != null)
                {
                    var relSection = ReadRelationships(relXml);
                    if (relSection != null) sb.Append(relSection);
                }

                // Forms
                foreach (var formType in new[] { "main", "quick", "card" })
                {
                    var formDir = Path.Combine(entityDir, "FormXml", formType);
                    if (!Directory.Exists(formDir)) continue;
                    foreach (var formFile in Directory.EnumerateFiles(formDir, "*.xml").OrderBy(f => f))
                    {
                        var formXml = TryReadFile(formFile);
                        if (formXml == null) continue;
                        var formSection = ReadForm(formXml, formType);
                        if (formSection != null) sb.Append(formSection);
                    }
                }

                // Views
                var savedQueriesDir = Path.Combine(entityDir, "SavedQueries");
                if (Directory.Exists(savedQueriesDir))
                {
                    foreach (var viewFile in Directory.EnumerateFiles(savedQueriesDir, "*.xml").OrderBy(f => f))
                    {
                        var viewXml = TryReadFile(viewFile);
                        if (viewXml == null) continue;
                        var viewSection = ReadView(viewXml);
                        if (viewSection != null) sb.Append(viewSection);
                    }
                }
            }
        }

        // Workflows
        var workflowsPath = Path.Combine(packageSrcPath, "Workflows");
        var workflowSection = ReadWorkflows(workflowsPath);
        if (workflowSection != null) sb.Append(workflowSection);

        // Plugin steps
        var stepsPath = Path.Combine(packageSrcPath, "SdkMessageProcessingSteps");
        var stepsSection = ReadPluginSteps(stepsPath);
        if (stepsSection != null) sb.Append(stepsSection);

        // Connection references
        var customizationsPath = Path.Combine(packageSrcPath, "Other", "Customizations.xml");
        var connRefsXml = TryReadFile(customizationsPath);
        if (connRefsXml != null)
        {
            var connRefsSection = ReadConnectionReferences(connRefsXml);
            if (connRefsSection != null) sb.Append(connRefsSection);
        }

        return sb.ToString();
    }

    static string? TryReadFile(string path)
    {
        if (!File.Exists(path)) return null;
        try { return File.ReadAllText(path); }
        catch (IOException) { return null; }
        catch (UnauthorizedAccessException) { return null; }
    }

    // ── U3: Solution header ──────────────────────────────────────────────────

    internal static string? ReadSolutionHeader(string? xml)
    {
        if (xml == null) return null;
        try
        {
            var doc = XDocument.Parse(xml.TrimStart('﻿'));
            var manifest = doc.Root?.Element("SolutionManifest");
            if (manifest == null) return null;

            var uniqueName   = (string?)manifest.Element("UniqueName") ?? string.Empty;
            var displayName  = GetLocalizedName(manifest.Element("LocalizedNames")) ?? uniqueName;
            var version      = (string?)manifest.Element("Version") ?? string.Empty;
            var prefix       = (string?)manifest.Element("Publisher")?.Element("CustomizationPrefix") ?? string.Empty;

            var sb = new StringBuilder();
            sb.AppendLine("## Solution");
            sb.AppendLine();
            sb.AppendLine($"| | |");
            sb.AppendLine($"|-|-|");
            sb.AppendLine($"| Display name | {displayName} |");
            sb.AppendLine($"| Unique name | {uniqueName} |");
            sb.AppendLine($"| Version | {version} |");
            sb.AppendLine($"| Publisher prefix | {prefix} |");
            sb.AppendLine();
            return sb.ToString();
        }
        catch (XmlException) { return null; }
    }

    internal static string ReadPublisherPrefix(string? xml)
    {
        if (xml == null) return string.Empty;
        try
        {
            var doc = XDocument.Parse(xml.TrimStart('﻿'));
            return (string?)doc.Root?.Element("SolutionManifest")?.Element("Publisher")?.Element("CustomizationPrefix") ?? string.Empty;
        }
        catch (XmlException) { return string.Empty; }
    }

    // ── U4: Entity, attributes, option sets ─────────────────────────────────

    internal static string? ReadEntity(string? xml, string publisherPrefix = "")
    {
        if (xml == null) return null;
        try
        {
            var doc = XDocument.Parse(xml.TrimStart('﻿'));
            // Root-level <Name LocalizedName="Account">account</Name> holds names for all entity XML shapes
            var rootNameEl  = doc.Root?.Element("Name");
            var logicalName = (string?)rootNameEl ?? string.Empty;
            var displayName = (string?)rootNameEl?.Attribute("LocalizedName") ?? logicalName;

            // Full entity XML has <EntityInfo><entity Name="Account">...</entity></EntityInfo>
            var entity = doc.Root?.Element("EntityInfo")?.Element("entity")
                      ?? doc.Root?.Element("entity");

            var entitySet     = (string?)entity?.Element("EntitySetName") ?? string.Empty;
            var ownershipType = (string?)entity?.Element("OwnershipTypeMask") ?? (string?)entity?.Element("OwnershipType") ?? string.Empty;
            var isActivity    = (string?)entity?.Element("IsActivity") switch { "1" => "true", "0" => "false", var v => v ?? "false" };

            var isCustomEntity = !string.IsNullOrEmpty(publisherPrefix)
                              && logicalName.StartsWith(publisherPrefix + "_", StringComparison.OrdinalIgnoreCase);
            var docsUrl = isCustomEntity
                ? null
                : $"https://learn.microsoft.com/en-us/power-apps/developer/data-platform/reference/entities/{logicalName.ToLowerInvariant()}";

            var activitySuffix = isActivity == "true" ? " — activity" : string.Empty;
            var docsSuffix = docsUrl != null ? $" — [docs]({docsUrl})" : string.Empty;
            var sb = new StringBuilder();
            sb.AppendLine($"## Entity: {displayName} (`{logicalName}` / `{entitySet}`){activitySuffix}{docsSuffix}");
            sb.AppendLine();

            var attributes = entity?.Descendants("attribute").ToList() ?? [];
            if (attributes.Count > 0)
            {
                sb.AppendLine("### Attributes");
                sb.AppendLine();
                sb.AppendLine("| Logical name | Display name | Type | Required | Custom | Notes |");
                sb.AppendLine("|---|---|---|---|---|---|");

                foreach (var attr in attributes)
                {
                    var attrName    = (string?)attr.Element("LogicalName") ?? (string?)attr.Element("Name") ?? string.Empty;
                    var attrDisplay = GetLocalizedName(attr.Element("displaynames")) ?? attrName;
                    var attrType    = (string?)attr.Element("Type") ?? string.Empty;
                    var required    = (string?)attr.Element("RequiredLevel") ?? string.Empty;
                    var isCustom    = (string?)attr.Element("IsCustomField") == "1" ? "yes" : "no";
                    var description = StripGuids(
                        attr.Element("Descriptions")?.Elements("Description")
                            .FirstOrDefault(d => (string?)d.Attribute("languagecode") == "1033")
                            ?.Attribute("description")?.Value ?? string.Empty);
                    var notes = new List<string>();
                    if (!string.IsNullOrEmpty(description)) notes.Add(description);

                    // ValidFor restrictions (PAC element names include "Api" suffix)
                    if ((string?)attr.Element("ValidForCreateApi") == "0") notes.Add("read-only on create");
                    if ((string?)attr.Element("ValidForUpdateApi") == "0") notes.Add("read-only on update");

                    sb.AppendLine($"| `{attrName}` | {attrDisplay} | {attrType} | {required} | {isCustom} | {string.Join("; ", notes)} |");

                    // Inline option set values
                    var options = attr.Descendants("option").ToList();
                    if (options.Count > 0)
                    {
                        foreach (var opt in options)
                        {
                            var val   = (string?)opt.Attribute("value") ?? string.Empty;
                            var label = GetLocalizedName(opt.Element("Labels") ?? opt.Element("labels"))
                                     ?? (string?)opt.Attribute("label")
                                     ?? val;
                            sb.AppendLine($"| | ↳ `{val}` = {label} | | | | |");
                        }
                    }
                }
                sb.AppendLine();
            }

            return sb.ToString();
        }
        catch (XmlException) { return null; }
    }

    // ── U5: Relationships ────────────────────────────────────────────────────

    internal static string? ReadRelationships(string? xml)
    {
        if (xml == null) return null;
        try
        {
            var doc = XDocument.Parse(xml.TrimStart('﻿'));
            var relationships = doc.Descendants("EntityRelationship").ToList();
            if (relationships.Count == 0) return null;

            var sb = new StringBuilder();
            sb.AppendLine("### Relationships");
            sb.AppendLine();
            sb.AppendLine("| Schema name | Type | Related entity | Lookup / intersect |");
            sb.AppendLine("|---|---|---|---|");

            foreach (var rel in relationships)
            {
                var schemaName = (string?)rel.Element("SchemaName") ?? string.Empty;
                var relType    = (string?)rel.Element("RelationshipType") ?? string.Empty;

                if (relType.Equals("OneToManyRelationship", StringComparison.OrdinalIgnoreCase) ||
                    relType.Equals("ManyToOneRelationship",  StringComparison.OrdinalIgnoreCase))
                {
                    var referenced  = (string?)rel.Element("ReferencedEntity") ?? string.Empty;
                    var referencing = (string?)rel.Element("ReferencingEntity") ?? string.Empty;
                    var lookup      = (string?)rel.Element("ReferencingAttribute") ?? string.Empty;
                    var related     = relType.Contains("OneToMany", StringComparison.OrdinalIgnoreCase) ? referencing : referenced;
                    sb.AppendLine($"| `{schemaName}` | {relType} | `{related}` | `{lookup}` |");
                }
                else // N:N
                {
                    var entity1   = (string?)rel.Element("Entity1LogicalName") ?? string.Empty;
                    var entity2   = (string?)rel.Element("Entity2LogicalName") ?? string.Empty;
                    var intersect = (string?)rel.Element("IntersectEntityName") ?? string.Empty;
                    sb.AppendLine($"| `{schemaName}` | ManyToManyRelationship | `{entity1}` / `{entity2}` | `{intersect}` |");
                }
            }
            sb.AppendLine();
            return sb.ToString();
        }
        catch (XmlException) { return null; }
    }

    // ── U6: Forms ────────────────────────────────────────────────────────────

    internal static string? ReadForm(string? xml, string formType = "main")
    {
        if (xml == null) return null;
        try
        {
            var doc = XDocument.Parse(xml.TrimStart('﻿'));
            var formName = GetLocalizedName(doc.Root?.Element("LocalizedNames"))
                        ?? (string?)doc.Root?.Attribute("Name")
                        ?? formType;

            var fields = new List<(string tab, string section, string field)>();

            foreach (var tab in doc.Descendants("tab"))
            {
                var tabLabel = GetLocalizedName(tab.Element("labels")) ?? (string?)tab.Attribute("name") ?? "Tab";
                foreach (var section in tab.Descendants("section"))
                {
                    var secLabel = GetLocalizedName(section.Element("labels")) ?? (string?)section.Attribute("name") ?? "Section";
                    foreach (var cell in section.Descendants("cell"))
                    {
                        if ((string?)cell.Attribute("invisible") == "true") continue;
                        var fieldName = (string?)cell.Attribute("datafieldname")
                                     ?? (string?)cell.Element("control")?.Attribute("datafieldname");
                        if (string.IsNullOrEmpty(fieldName)) continue;
                        if (GuidPattern.IsMatch(fieldName)) continue;
                        fields.Add((tabLabel, secLabel, fieldName));
                    }
                }
            }

            if (fields.Count == 0) return null;

            var sb = new StringBuilder();
            sb.AppendLine($"### Form: {formName} ({formType})");
            sb.AppendLine();

            foreach (var tabGroup in fields.GroupBy(f => f.tab))
            {
                sb.AppendLine($"**{tabGroup.Key}**");
                sb.AppendLine();
                foreach (var secGroup in tabGroup.GroupBy(f => f.section))
                {
                    sb.AppendLine($"- {secGroup.Key}: {string.Join(", ", secGroup.Select(f => $"`{f.field}`"))}");
                }
                sb.AppendLine();
            }
            sb.AppendLine();
            return sb.ToString();
        }
        catch (XmlException) { return null; }
    }

    // ── U7: Views (SavedQueries) ─────────────────────────────────────────────

    internal static string? ReadView(string? xml)
    {
        if (xml == null) return null;
        try
        {
            var doc = XDocument.Parse(xml.TrimStart('﻿'));
            // PAC wraps in <savedqueries>; test fixtures use <savedquery> as root directly
            var savedQuery = doc.Root?.Element("savedquery") ?? doc.Root;
            var viewName = GetLocalizedName(savedQuery?.Element("LocalizedNames"))
                        ?? (string?)savedQuery?.Attribute("name")
                        ?? "View";

            // Columns from layoutxml — strip auto-generated GUID link-entity aliases (a_<32hex>.field)
            var guidAliasPrefix = new System.Text.RegularExpressions.Regex(@"^a_[0-9a-f]{32}\.", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            var columns = doc.Descendants("cell")
                .Select(c => (string?)c.Attribute("name"))
                .Where(n => !string.IsNullOrEmpty(n))
                .Select(n => guidAliasPrefix.Replace(n!, string.Empty))
                .Distinct()
                .ToList();

            // Filter summary from fetchxml
            var conditions = doc.Descendants("condition")
                .Where(c => c.Attribute("attribute") != null)
                .Select(c => {
                    var attr = c.Attribute("attribute")!.Value;
                    var op   = c.Attribute("operator")?.Value ?? string.Empty;
                    var val  = c.Attribute("value")?.Value;
                    return val != null ? $"`{attr}` {op} `{val}`" : $"`{attr}` {op}";
                })
                .Where(s => !string.IsNullOrEmpty(s))
                .ToList();

            // Linked entities
            var linkedEntities = doc.Descendants("link-entity")
                .Select(l => (string?)l.Attribute("name"))
                .Where(n => !string.IsNullOrEmpty(n))
                .Distinct()
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine($"### View: {viewName}");
            sb.AppendLine();
            if (columns.Count > 0)
            {
                sb.AppendLine($"Columns: {string.Join(", ", columns.Select(c => $"`{c}`"))}");
                sb.AppendLine();
            }
            if (conditions.Count > 0)
            {
                sb.AppendLine($"Filter: {string.Join(", ", conditions)}");
                sb.AppendLine();
            }
            if (linkedEntities.Count > 0)
            {
                sb.AppendLine($"Links: {string.Join(", ", linkedEntities.Select(e => $"`{e}`"))}");
                sb.AppendLine();
            }
            return sb.ToString();
        }
        catch (XmlException) { return null; }
    }

    // ── U8: Workflows ────────────────────────────────────────────────────────

    internal static string? ReadWorkflows(string? folderPath)
    {
        if (folderPath == null || !Directory.Exists(folderPath)) return null;

        var rows = new List<string>();
        // PAC writes workflow metadata as *.data.xml — raw *.json and *.xaml workflow files are not metadata
        foreach (var file in Directory.EnumerateFiles(folderPath, "*.xml", SearchOption.AllDirectories)
                                       .Where(f => f.EndsWith(".data.xml", StringComparison.OrdinalIgnoreCase))
                                       .OrderBy(f => f))
        {
            var xml = TryReadFile(file);
            if (xml == null) continue;
            try
            {
                var doc = XDocument.Parse(xml.TrimStart('﻿'));
                var rawName    = (string?)doc.Root?.Attribute("Name") ?? GetLocalizedName(doc.Root?.Element("LocalizedNames")) ?? Path.GetFileNameWithoutExtension(file);
                var name       = rawName.Replace("|", "\\|");
                var stateCode  = (string?)doc.Root?.Attribute("StateCode") ?? (string?)doc.Root?.Element("StateCode");
                var state      = stateCode == "1" ? "Active" : stateCode == "0" ? "Inactive" : stateCode ?? string.Empty;
                var trigger    = (string?)doc.Root?.Attribute("PrimaryEntity") ?? (string?)doc.Root?.Element("PrimaryEntity") ?? string.Empty;
                rows.Add($"| {name} | {state} | `{trigger}` |");
            }
            catch (XmlException) { }
        }

        if (rows.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("## Workflows");
        sb.AppendLine();
        sb.AppendLine("| Name | State | Trigger entity |");
        sb.AppendLine("|---|---|---|");
        foreach (var row in rows) sb.AppendLine(row);
        sb.AppendLine();
        return sb.ToString();
    }

    // ── U8: Plugin steps ────────────────────────────────────────────────────

    internal static string? ReadPluginSteps(string? folderPath)
    {
        if (folderPath == null || !Directory.Exists(folderPath)) return null;

        var rows = new List<string>();
        foreach (var file in Directory.EnumerateFiles(folderPath, "*.xml").OrderBy(f => f))
        {
            var xml = TryReadFile(file);
            if (xml == null) continue;
            try
            {
                var doc = XDocument.Parse(xml.TrimStart('﻿'));
                // Message is not a separate element — extract from step Name: "PluginClass: Update of contact"
                var stepName = (string?)doc.Root?.Attribute("Name") ?? string.Empty;
                var afterColon = stepName.Contains(": ") ? stepName[(stepName.IndexOf(": ") + 2)..] : stepName;
                var message = afterColon.Contains(" of ") ? afterColon[..afterColon.IndexOf(" of ")] : afterColon;
                var entity  = (string?)doc.Root?.Attribute("PrimaryObjectTypeCode")
                           ?? (string?)doc.Root?.Element("PrimaryObjectTypeCode")
                           ?? (string?)doc.Root?.Element("PrimaryEntity")
                           ?? string.Empty;
                var stageRaw = (string?)doc.Root?.Attribute("Stage") ?? (string?)doc.Root?.Element("Stage") ?? string.Empty;
                var modeRaw  = (string?)doc.Root?.Attribute("Mode") ?? (string?)doc.Root?.Element("Mode") ?? string.Empty;
                var fullType = (string?)doc.Root?.Attribute("PluginTypeName") ?? (string?)doc.Root?.Element("PluginTypeName") ?? string.Empty;
                var className = fullType.Contains(',') ? fullType[..fullType.IndexOf(',')].Split('.').LastOrDefault() ?? fullType : fullType.Split('.').LastOrDefault() ?? fullType;

                var stage = stageRaw switch { "10" => "pre-validation", "20" => "pre-operation", "40" => "post-operation", _ => stageRaw };
                var mode  = modeRaw  switch { "0"  => "sync",           "1"  => "async",          _ => modeRaw  };

                rows.Add($"| {message} | `{entity}` | {stage} | {mode} | {className} |");
            }
            catch (XmlException) { }
        }

        if (rows.Count == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("## Plugin Steps");
        sb.AppendLine();
        sb.AppendLine("| Message | Entity | Stage | Mode | Class |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (var row in rows) sb.AppendLine(row);
        sb.AppendLine();
        return sb.ToString();
    }

    // ── U8: Connection references ────────────────────────────────────────────

    internal static string? ReadConnectionReferences(string? xml)
    {
        if (xml == null) return null;
        try
        {
            var doc = XDocument.Parse(xml.TrimStart('﻿'));

            // PAC unpacks connection references as <connectionreference> elements inside <connectionreferences>
            var refs = doc.Descendants("connectionreference").ToList();
            if (refs.Count == 0) return null;

            var sb = new StringBuilder();
            sb.AppendLine("## Connection References");
            sb.AppendLine();
            sb.AppendLine("| Logical name | Connector ID |");
            sb.AppendLine("|---|---|");

            foreach (var connRef in refs)
            {
                var displayName  = (string?)connRef.Element("connectionreferencelogicalname")
                                ?? (string?)connRef.Attribute("connectionreferencelogicalname")
                                ?? string.Empty;
                var connectorId  = (string?)connRef.Element("connectorid")
                                ?? (string?)connRef.Attribute("connectorid")
                                ?? string.Empty;
                sb.AppendLine($"| {displayName} | {connectorId} |");
            }
            sb.AppendLine();
            return sb.ToString();
        }
        catch (XmlException) { return null; }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    static string? GetLocalizedName(XElement? parent)
    {
        if (parent == null) return null;
        // Try <LocalizedName languagecode="1033" description="...">
        var ln = parent.Elements("LocalizedName")
                       .FirstOrDefault(e => (string?)e.Attribute("languagecode") == "1033")
              ?? parent.Elements("LocalizedName").FirstOrDefault();
        if (ln != null) return (string?)ln.Attribute("description");

        // Try <label languagecode="1033" description="...">
        var label = parent.Elements("label")
                          .FirstOrDefault(e => (string?)e.Attribute("languagecode") == "1033")
                 ?? parent.Elements("label").FirstOrDefault();
        if (label != null) return (string?)label.Attribute("description");

        // Try <displayname languagecode="1033" description="..."> (PAC attribute display names)
        var dn = parent.Elements("displayname")
                       .FirstOrDefault(e => (string?)e.Attribute("languagecode") == "1033")
              ?? parent.Elements("displayname").FirstOrDefault();
        return (string?)dn?.Attribute("description");
    }

    static string StripGuids(string text) =>
        string.IsNullOrEmpty(text) ? text : GuidPattern.Replace(text, string.Empty).Trim();
}
