using Flowline.Core.Models;
using Flowline.Core.Services;

namespace Flowline.Core.Tests;

public class FormEventAnnotationParserTests : IDisposable
{
    readonly string _dir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());

    public FormEventAnnotationParserTests() => Directory.CreateDirectory(_dir);

    public void Dispose()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, true);
    }

    string Write(string filename, string content)
    {
        var path = Path.Combine(_dir, filename);
        File.WriteAllText(path, content);
        return path;
    }

    [Fact]
    public void ParseAnnotations_OnLoadBareEntityAndQuotedForm_ReturnsAnnotationWithNullFunctionAndParameters()
    {
        var path = Write("form.js", "// flowline:onload account \"Account\"\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Equal([new FormEventAnnotation("account", "Account", FormEventType.OnLoad, null, null)], result.Annotations);
        Assert.Empty(result.MalformedLines);
    }

    [Fact]
    public void ParseAnnotations_OnLoadWithFunctionName_ReturnsFunctionNameAndNullParameters()
    {
        var path = Write("form.js", "// flowline:onload account Account CustomOnLoad\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        var annotation = Assert.Single(result.Annotations);
        Assert.Equal("account", annotation.Entity);
        Assert.Equal("Account", annotation.Form);
        Assert.Equal(FormEventType.OnLoad, annotation.Event);
        Assert.Equal("CustomOnLoad", annotation.FunctionName);
        Assert.Null(annotation.Parameters);
    }

    [Fact]
    public void ParseAnnotations_OnSaveWithQuotedFormAndFunctionParams_ReturnsAllFields()
    {
        var path = Write("form.js",
            "// flowline:onsave account \"Account form for Customer Card\" onSave(testParam1,testParam2)\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        var annotation = Assert.Single(result.Annotations);
        Assert.Equal("account", annotation.Entity);
        Assert.Equal("Account form for Customer Card", annotation.Form);
        Assert.Equal(FormEventType.OnSave, annotation.Event);
        Assert.Equal("onSave", annotation.FunctionName);
        Assert.Equal("testParam1,testParam2", annotation.Parameters);
    }

    [Fact]
    public void ParseAnnotations_ParametersWithSurroundingWhitespace_TrimmedInResult()
    {
        var path = Write("form.js", "// flowline:onsave account Account onSave(a, b, c)\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        var annotation = Assert.Single(result.Annotations);
        Assert.Equal("a,b,c", annotation.Parameters);
    }

    [Fact]
    public void ParseAnnotations_BangLineComment_RecognizedIdenticallyToLineComment()
    {
        var path = Write("form.js", "//! flowline:onload account Account\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Equal([new FormEventAnnotation("account", "Account", FormEventType.OnLoad, null, null)], result.Annotations);
    }

    [Fact]
    public void ParseAnnotations_BangBlockComment_RecognizedIdenticallyToLineComment()
    {
        var path = Write("form.js", "/*! flowline:onload account Account */\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Equal([new FormEventAnnotation("account", "Account", FormEventType.OnLoad, null, null)], result.Annotations);
    }

    [Fact]
    public void ParseAnnotations_AfterLeadingBannerBlockComment_StillCollected()
    {
        // Reproduces the flowline:depends bug class documented in webresource-dependency-registration-patterns.md
        // lesson 8: a non-"//" banner comment on early lines must not stop the scan before it reaches
        // the annotation later in the file.
        var lines = new List<string> { "/**", "  * Generated by Rollup", "  */", "(function () {" };
        lines.AddRange(Enumerable.Repeat("code();", 45));
        lines.Add("// flowline:onload account Account");
        lines.Add("})();");
        var path = Write("form.js", string.Join('\n', lines));

        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Equal([new FormEventAnnotation("account", "Account", FormEventType.OnLoad, null, null)], result.Annotations);
    }

    [Fact]
    public void ParseAnnotations_BareFormNameNoSpacesNoQuotes_Recognized()
    {
        var path = Write("form.js", "// flowline:onload account Account\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Equal([new FormEventAnnotation("account", "Account", FormEventType.OnLoad, null, null)], result.Annotations);
    }

    [Fact]
    public void ParseAnnotations_TwoAnnotationsDifferentEvents_BothParsedInOrder()
    {
        var path = Write("form.js",
            "// flowline:onload account Account\n// flowline:onsave account Account\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Equal(2, result.Annotations.Count);
        Assert.Equal(FormEventType.OnLoad, result.Annotations[0].Event);
        Assert.Equal(FormEventType.OnSave, result.Annotations[1].Event);
    }

    [Fact]
    public void ParseAnnotations_MissingForm_NotMatchedButFlaggedMalformed()
    {
        var path = Write("form.js", "// flowline:onload account\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Empty(result.Annotations);
        Assert.Single(result.MalformedLines);
    }

    [Fact]
    public void ParseAnnotations_NoAnnotations_ReturnsEmpty()
    {
        var path = Write("form.js", "// just a regular comment\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Empty(result.Annotations);
        Assert.Empty(result.MalformedLines);
    }

    [Fact]
    public void ParseAnnotations_SingleQuotedFormNameWithSpaces_Recognized()
    {
        // R3: single quotes are an accepted alternative to double quotes for a multi-word form name —
        // matches JS's own string-literal convention (no grammar conflict, nothing else in the annotation
        // syntax uses either quote character). Must parse successfully, not be flagged as malformed.
        var path = Write("form.js", "// flowline:onload account 'Account Quick Create'\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        var annotation = Assert.Single(result.Annotations);
        Assert.Equal("Account Quick Create", annotation.Form);
        Assert.Empty(result.MalformedLines);
    }

    [Fact]
    public void ParseAnnotations_MismatchedQuoteCharacters_NotMatchedButFlaggedMalformed()
    {
        // A form name delimited by mismatched quote characters (opens single, closes double) is genuinely
        // malformed — R3 accepts single or double, but not mixed — and must be surfaced, not silently
        // dropped like an ordinary non-matching comment.
        var path = Write("form.js", "// flowline:onload account 'Account Quick Create\"\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        Assert.Empty(result.Annotations);
        Assert.Single(result.MalformedLines);
    }

    [Fact]
    public void ParseAnnotations_MalformedAndValidLinesInSameFile_BothReportedIndependently()
    {
        var path = Write("form.js",
            "//! flowline:onload account AutomateValue\n//! flowline:onload account\ncode();");
        var result = FormEventAnnotationParser.ParseAnnotations(path);

        var annotation = Assert.Single(result.Annotations);
        Assert.Equal("AutomateValue", annotation.Form);
        Assert.Single(result.MalformedLines);
    }
}
